[window]
opacity = 0.8
decorations = "transparent"
padding = { x = 10, y = 10 }

[font]
size = 12

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"