[window]
opacity = 0.8
decorations = "full"
padding = { x = 0, y = 0 }

[font]
size = 14

[font.offset]
x = 1
y = 2

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

#### FONT SIZE #####################################################
[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"
####################################################################


#### INTERRUPT #####################################################
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"
####################################################################


#### COPY & PASTE ##################################################
[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"
